### ISSUE TITLE
[segfault] Segfault sending an outgoing message with attachment.

### ISSUE THREAD

**Issue by skx** [lumail/lumail2#218]
This has worked a lot in the past, today it happened when mailing [my blog](https://blog.steve.fi/) theme to Amar.

If reproducible this should be treated as urgent.  If not then .. it is still a major issue.

**Comment by skx** [comment]
Still present even after commit 937a78690c7857aa547e1eb778e5d15b2a882ca7, which I made to resolve #219.

With the address-sanitizer in place we see this:


      =================================================================
      ==2739==ERROR: AddressSanitizer: attempting double-free on 0x616000068780 in thread T0:
          #0 0x7f8674837527 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x54527)
          #1 0x7f867256d734 in fclose (/lib/x86_64-linux-gnu/libc.so.6+0x69734)
          #2 0x4d998c in CMessage::add_attachments(std::vector<std::string, std::allocator<std::string> >) src/message.cc:1145
          #3 0x467634 in l_CMessage_add_attachments(lua_State*) src/message_lua.cc:326
          #4 0x7f86745bcc3c (/usr/lib/x86_64-linux-gnu/liblua5.2.so.0+0xcc3c)
          #5 0x7f86745c859c (/usr/lib/x86_64-linux-gnu/liblua5.2.so.0+0x1859c)
          #6 0x7f86745bcfa7 (/usr/lib/x86_64-linux-gnu/liblua5.2.so.0+0xcfa7)
          #7 0x7f86745bc5be (/usr/lib/x86_64-linux-gnu/liblua5.2.so.0+0xc5be)
          #8 0x7f86745bd200 (/usr/lib/x86_64-linux-gnu/liblua5.2.so.0+0xd200)
          #9 0x7f86745b9185 in lua_pcallk (/usr/lib/x86_64-linux-gnu/liblua5.2.so.0+0x9185)
          #10 0x4886b5 in CLua::execute(std::string) src/lua.cc:187
          #11 0x474e4f in CScreen::on_keypress(std::string) src/screen.cc:1227
          #12 0x4771ed in CScreen::run_main_loop() src/screen.cc:244
          #13 0x41d4f2 in main src/lumail2.cc:220
          #14 0x7f8672525b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
          #15 0x41e278 (/home/skx/Repos/personal/lumail2/lumail2-debug+0x41e278)

So the cause  is closing a file-handle that we've passed over to gmime.  D'oh.
